# Generated by Django 3.1.3 on 2020-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='diagnosis',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'Pneumonia'), (2, 'COVID')], max_length=15),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='uploaded_image',
            field=models.ImageField(default='default_image.gif', upload_to='uploads/'),
        ),
    ]
