# Generated by Django 3.1.3 on 2020-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201209_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='uploaded_image',
            field=models.BinaryField(),
        ),
    ]
