# Generated by Django 3.1.3 on 2020-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='uploaded_image',
            field=models.ImageField(default='default_image.gif', upload_to='uploads/'),
        ),
    ]
