# Generated by Django 3.1.3 on 2020-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='processed_image',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='prediction',
            name='processed_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='uploaded_image_url',
            field=models.URLField(null=True),
        ),
    ]
