# Generated by Django 3.1.3 on 2020-12-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201209_1122'),
        ('main', '0005_auto_20201209_1657'),
    ]

    operations = [
    ]
